version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter.dockerfile
    volumes:
      - ./:/home/jovyan/work
    environment:
      - PASSWORD=password
      - TOKEN=token
    ports:
      - 8888:8888
